name: Update games list gist
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  updateGamesList:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Generate crackwatch-games-list.json
        run: |
          python ./.github/workflows/update-bot/generateJson.py
      - name: Deploy to Gist
        uses: exuanbo/actions-deploy-gist@v1.0.3
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 6eae417c09ebe0035d14f767569afd24
          gist_file_name: crackwatch-games-list.json
          file_path: ./crackwatch-games-list.json